name: ridez

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      # - .:/app  # For development (auto reload on code changes)
      - backend_data:/app
    environment:
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

volumes:
  backend_data:
